// Generated by scripts/gp-to-licks.mjs from "comfortably-numb-solo.gp3" — do not edit by hand.
// {"title":"Comfortably Numb (solo)","artist":"Pink Floyd","tempo":65,"barCount":12,"tracks":[{"index":0,"name":"Guitar 1","program":30,"percussion":false,"noteCount":98},{"index":1,"name":"Guitar 2","program":25,"percussion":false,"noteCount":154}]}
export const comfortablyNumb = [
 {
  "kind": "solo",
  "id": "comfortablyNumb-solo",
  "title": {
   "en": "Comfortably Numb",
   "he": "Comfortably Numb"
  },
  "artist": "Pink Floyd",
  "genre": "rock",
  "level": "advanced",
  "key": "B",
  "scale": "B minor pentatonic",
  "bpm": 65,
  "source": "user",
  "credit": "Pink Floyd — Comfortably Numb, first solo (David Gilmour) · Guitar Pro file",
  "about": {
   "en": "David Gilmour's first solo, read directly from your Guitar Pro file: melodic phrasing, half- and whole-step bends, pre-bend releases and vibrato. Work section by section, then play the whole solo.",
   "he": "הסולו הראשון של דייוויד גילמור, נקרא ישירות מקובץ ה-Guitar Pro שלך: פרייזינג מלודי, כפיפות של חצי טון וטון שלם, שחרורים מכפיפה מוקדמת וויברטו. עבדו קטע אחרי קטע, ואז נגנו את הסולו כולו."
  },
  "simplified": false,
  "tuningShift": 0,
  "sections": [
   {
    "fromBeat": 0,
    "toBeat": 5,
    "label": {
     "en": "Bars 1–2",
     "he": "תיבות 1–2"
    }
   },
   {
    "fromBeat": 5,
    "toBeat": 13,
    "label": {
     "en": "Bars 3–4",
     "he": "תיבות 3–4"
    }
   },
   {
    "fromBeat": 13,
    "toBeat": 21,
    "label": {
     "en": "Bars 5–6",
     "he": "תיבות 5–6"
    }
   },
   {
    "fromBeat": 21,
    "toBeat": 29,
    "label": {
     "en": "Bars 7–8",
     "he": "תיבות 7–8"
    }
   },
   {
    "fromBeat": 29,
    "toBeat": 37,
    "label": {
     "en": "Bars 9–10",
     "he": "תיבות 9–10"
    }
   },
   {
    "fromBeat": 37,
    "toBeat": 46,
    "label": {
     "en": "Bars 11–12",
     "he": "תיבות 11–12"
    }
   }
  ],
  "barPhase": 1,
  "gpRef": {
   "track": 0,
   "tickStart": 2880
  },
  "notes": [
   {
    "start": 0.75,
    "duration": 0.0833,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 0.8333,
    "duration": 0.0833,
    "string": 4,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 0.9167,
    "duration": 0.0833,
    "string": 5,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 1,
    "duration": 2.5,
    "string": 5,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 3.75,
    "duration": 0.5,
    "string": 5,
    "fret": 14,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 4.25,
    "duration": 0.5,
    "string": 5,
    "fret": 14,
    "technique": "release",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 4.75,
    "duration": 1.4167,
    "string": 4,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": true
   },
   {
    "start": 6.1667,
    "duration": 0.1667,
    "string": 4,
    "fret": 15,
    "technique": "release",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 6.3333,
    "duration": 0.3333,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 6.6667,
    "duration": 0.3333,
    "string": 4,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 7,
    "duration": 0.375,
    "string": 4,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 7.375,
    "duration": 0.125,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 7.5,
    "duration": 0.5,
    "string": 2,
    "fret": 14,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 8,
    "duration": 0.75,
    "string": 2,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 8.75,
    "duration": 0.25,
    "string": 2,
    "fret": 12,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 9,
    "duration": 2.5,
    "string": 2,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 11.5,
    "duration": 0.25,
    "string": 4,
    "fret": 0,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 11.75,
    "duration": 0.0833,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 11.8333,
    "duration": 0.0833,
    "string": 4,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 11.9167,
    "duration": 0.0833,
    "string": 5,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 12,
    "duration": 0.3333,
    "string": 5,
    "fret": 14,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 12.3333,
    "duration": 0.3333,
    "string": 5,
    "fret": 14,
    "technique": "release",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 12.6667,
    "duration": 0.3333,
    "string": 5,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 13,
    "duration": 1.3333,
    "string": 4,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 14.3333,
    "duration": 0.3333,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 14.6667,
    "duration": 0.3333,
    "string": 4,
    "fret": 14,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 15,
    "duration": 0.3333,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 15.3333,
    "duration": 0.3333,
    "string": 2,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 15.6667,
    "duration": 0.2083,
    "string": 2,
    "fret": 12,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 16,
    "duration": 0.2083,
    "string": 2,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 16.3333,
    "duration": 0.3333,
    "string": 2,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 16.6667,
    "duration": 0.2083,
    "string": 1,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 17,
    "duration": 2.3333,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 19.3333,
    "duration": 0.3333,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 19.6667,
    "duration": 0.3333,
    "string": 2,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 20,
    "duration": 0.5,
    "string": 2,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 20.75,
    "duration": 0.125,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 20.875,
    "duration": 0.125,
    "string": 3,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 21,
    "duration": 0.5,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 21.5,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 21.75,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": "pull",
    "vibrato": true
   },
   {
    "start": 22,
    "duration": 1.5,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 23.5,
    "duration": 0.125,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 23.625,
    "duration": 0.125,
    "string": 3,
    "fret": 7,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 23.75,
    "duration": 0.125,
    "string": 2,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 23.875,
    "duration": 0.125,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 24,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 24.25,
    "duration": 0.25,
    "string": 3,
    "fret": 11,
    "technique": "bend",
    "bend": 0.5,
    "vibrato": false
   },
   {
    "start": 24.75,
    "duration": 0.25,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 25,
    "duration": 1,
    "string": 3,
    "fret": 11,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 26,
    "duration": 0.5,
    "string": 3,
    "fret": 11,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 26.875,
    "duration": 0.125,
    "string": 5,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 27,
    "duration": 0.3333,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 27.3333,
    "duration": 0.3333,
    "string": 5,
    "fret": 14,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 27.6667,
    "duration": 0.3333,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 28,
    "duration": 0.3333,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 28.3333,
    "duration": 0.3333,
    "string": 4,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 28.6667,
    "duration": 0.3333,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 29,
    "duration": 1,
    "string": 2,
    "fret": 12,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 30,
    "duration": 0.5,
    "string": 2,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 30.5,
    "duration": 0.5,
    "string": 2,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 31,
    "duration": 1.25,
    "string": 2,
    "fret": 9,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 32.25,
    "duration": 0.125,
    "string": 2,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 32.375,
    "duration": 0.125,
    "string": 2,
    "fret": 9,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 32.5,
    "duration": 2.5,
    "string": 2,
    "fret": 7,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 36.25,
    "duration": 2,
    "string": 3,
    "fret": 9,
    "technique": "bend",
    "bend": 3,
    "vibrato": false
   },
   {
    "start": 38.25,
    "duration": 0.5,
    "string": 3,
    "fret": 9,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 38.75,
    "duration": 0.125,
    "string": 3,
    "fret": 9,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 38.875,
    "duration": 0.125,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 39,
    "duration": 1.2083,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 40.3333,
    "duration": 0.3333,
    "string": 2,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 40.6667,
    "duration": 0.3333,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 41,
    "duration": 4,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   }
  ],
  "gpUrl": "/gp/comfortably-numb-solo.gp3"
 }
];
