// Generated by scripts/gp-to-licks.mjs from "november-rain.gp5" — do not edit by hand.
// {"title":"November Rain","artist":"","tempo":80,"barCount":35,"tracks":[{"index":0,"name":"Voice (Axl)","program":81,"percussion":false,"noteCount":64},{"index":1,"name":"Piano (Axl)","program":0,"percussion":false,"noteCount":144},{"index":2,"name":"Guitar 1 (Slash)","program":29,"percussion":false,"noteCount":272},{"index":3,"name":"Guitar 2 (Izzy)","program":26,"percussion":false,"noteCount":94},{"index":4,"name":"Guitar 3 (Slash)","program":25,"percussion":false,"noteCount":63},{"index":5,"name":"Guitar 4 (Izzy)","program":29,"percussion":false,"noteCount":110},{"index":6,"name":"Strings 1","program":48,"percussion":false,"noteCount":42},{"index":7,"name":"Strings 2","program":48,"percussion":false,"noteCount":175},{"index":8,"name":"Bass (Duff)","program":34,"percussion":false,"noteCount":149},{"index":9,"name":"Drums (Matt)","program":0,"percussion":true,"noteCount":283}]}
export const novemberRain = [
 {
  "kind": "solo",
  "id": "novemberRain-solo",
  "title": {
   "en": "November Rain",
   "he": "November Rain"
  },
  "artist": "Guns N' Roses",
  "genre": "rock",
  "level": "advanced",
  "key": "F (Eb tuning)",
  "scale": "F major / D minor pentatonic",
  "bpm": 80,
  "source": "user",
  "credit": "Guns N' Roses — November Rain, Guitar 1 (Slash) · Guitar Pro file",
  "about": {
   "en": "Slash's solo from your Guitar Pro file (guitar tuned down a half step): singing pre-bends and releases, long held bends with vibrato and melodic pentatonic runs. Tune down to Eb before playing.",
   "he": "הסולו של סלאש מקובץ ה-Guitar Pro שלך (גיטרה בכיוון נמוך בחצי טון): כפיפות מוקדמות ושחרורים שרים, כפיפות ארוכות מוחזקות עם ויברטו וריצות פנטטוניות מלודיות. כווננו חצי טון למטה (Eb) לפני הנגינה."
  },
  "simplified": true,
  "tuningShift": -1,
  "sections": [
   {
    "fromBeat": 0,
    "toBeat": 4,
    "label": {
     "en": "Bars 1–2",
     "he": "תיבות 1–2"
    }
   },
   {
    "fromBeat": 4,
    "toBeat": 12,
    "label": {
     "en": "Bars 3–4",
     "he": "תיבות 3–4"
    }
   },
   {
    "fromBeat": 12,
    "toBeat": 20,
    "label": {
     "en": "Bars 5–6",
     "he": "תיבות 5–6"
    }
   },
   {
    "fromBeat": 20,
    "toBeat": 28,
    "label": {
     "en": "Bars 7–8",
     "he": "תיבות 7–8"
    }
   },
   {
    "fromBeat": 28,
    "toBeat": 36,
    "label": {
     "en": "Bars 9–10",
     "he": "תיבות 9–10"
    }
   },
   {
    "fromBeat": 36,
    "toBeat": 44,
    "label": {
     "en": "Bars 11–12",
     "he": "תיבות 11–12"
    }
   },
   {
    "fromBeat": 44,
    "toBeat": 52,
    "label": {
     "en": "Bars 13–14",
     "he": "תיבות 13–14"
    }
   },
   {
    "fromBeat": 52,
    "toBeat": 60,
    "label": {
     "en": "Bars 15–16",
     "he": "תיבות 15–16"
    }
   },
   {
    "fromBeat": 60,
    "toBeat": 68,
    "label": {
     "en": "Bars 17–18",
     "he": "תיבות 17–18"
    }
   },
   {
    "fromBeat": 68,
    "toBeat": 76,
    "label": {
     "en": "Bars 19–20",
     "he": "תיבות 19–20"
    }
   },
   {
    "fromBeat": 76,
    "toBeat": 84,
    "label": {
     "en": "Bars 21–22",
     "he": "תיבות 21–22"
    }
   },
   {
    "fromBeat": 84,
    "toBeat": 92,
    "label": {
     "en": "Bars 23–24",
     "he": "תיבות 23–24"
    }
   },
   {
    "fromBeat": 92,
    "toBeat": 100,
    "label": {
     "en": "Bars 25–26",
     "he": "תיבות 25–26"
    }
   },
   {
    "fromBeat": 100,
    "toBeat": 108,
    "label": {
     "en": "Bars 27–28",
     "he": "תיבות 27–28"
    }
   },
   {
    "fromBeat": 108,
    "toBeat": 116,
    "label": {
     "en": "Bars 29–30",
     "he": "תיבות 29–30"
    }
   },
   {
    "fromBeat": 116,
    "toBeat": 124,
    "label": {
     "en": "Bars 31–32",
     "he": "תיבות 31–32"
    }
   },
   {
    "fromBeat": 124,
    "toBeat": 132,
    "label": {
     "en": "Bars 33–34",
     "he": "תיבות 33–34"
    }
   },
   {
    "fromBeat": 132,
    "toBeat": 137,
    "label": {
     "en": "Bar 35",
     "he": "תיבה 35"
    }
   }
  ],
  "barPhase": 0,
  "gpRef": {
   "track": 2,
   "tickStart": 3840
  },
  "notes": [
   {
    "start": 0,
    "duration": 1.5,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 1.5,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 2.5,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 2.75,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "release",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 3.75,
    "duration": 0.25,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 4,
    "duration": 1.5,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 5.5,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 6.5,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 6.75,
    "duration": 0.75,
    "string": 4,
    "fret": 8,
    "technique": "release",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 7.5,
    "duration": 2,
    "string": 4,
    "fret": 5,
    "technique": "bend",
    "bend": 1,
    "vibrato": true
   },
   {
    "start": 9.5,
    "duration": 1.5,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 11,
    "duration": 1,
    "string": 4,
    "fret": 5,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 12,
    "duration": 1.5,
    "string": 4,
    "fret": 5,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 13.5,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 13.75,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 14,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 14.25,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 14.5,
    "duration": 0.125,
    "string": 4,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 14.75,
    "duration": 0.75,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 15.5,
    "duration": 0.5,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 16,
    "duration": 1.5,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 17.5,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 18.5,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 18.75,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "release",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 19.75,
    "duration": 0.25,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 20,
    "duration": 1.5,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 21.5,
    "duration": 1,
    "string": 4,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 22.5,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 22.75,
    "duration": 1.25,
    "string": 5,
    "fret": 8,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 24,
    "duration": 3,
    "string": 5,
    "fret": 10,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 27,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 27.25,
    "duration": 0.25,
    "string": 5,
    "fret": 10,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 27.5,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 27.75,
    "duration": 0.25,
    "string": 4,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 28,
    "duration": 0.25,
    "string": 5,
    "fret": 8,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 28.25,
    "duration": 1.75,
    "string": 4,
    "fret": 11,
    "technique": "bend",
    "bend": 2,
    "vibrato": true
   },
   {
    "start": 30,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 30.25,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 30.5,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 30.75,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 31,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 31.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 31.5,
    "duration": 0.5,
    "string": 5,
    "fret": 13,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 32,
    "duration": 2.5,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 34.5,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 34.75,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 35,
    "duration": 0.5,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 35.5,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 35.75,
    "duration": 0.125,
    "string": 5,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 35.875,
    "duration": 0.125,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 36,
    "duration": 1.5,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 37.5,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 37.75,
    "duration": 0.25,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 38,
    "duration": 1.5,
    "string": 4,
    "fret": 18,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 39.5,
    "duration": 0.25,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 39.75,
    "duration": 0.25,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 40,
    "duration": 0.5,
    "string": 4,
    "fret": 17,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 40.5,
    "duration": 1,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 41.5,
    "duration": 2,
    "string": 5,
    "fret": 19,
    "technique": "bend",
    "bend": 1,
    "vibrato": true
   },
   {
    "start": 43.5,
    "duration": 0.25,
    "string": 5,
    "fret": 19,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 43.75,
    "duration": 0.25,
    "string": 5,
    "fret": 19,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 44,
    "duration": 0.25,
    "string": 5,
    "fret": 19,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 44.25,
    "duration": 0.25,
    "string": 5,
    "fret": 17,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 44.5,
    "duration": 0.25,
    "string": 5,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 44.75,
    "duration": 0.25,
    "string": 5,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 45,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 45.25,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 45.5,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 45.75,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 46,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 46.25,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 46.5,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 46.75,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 47,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 47.25,
    "duration": 0.125,
    "string": 5,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 47.375,
    "duration": 0.125,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 47.5,
    "duration": 0.375,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 48,
    "duration": 2,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 50,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 50.25,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 50.5,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 50.75,
    "duration": 0.125,
    "string": 5,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 50.875,
    "duration": 0.125,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 51,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 51.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 51.5,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 51.75,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 52,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 52.25,
    "duration": 0.125,
    "string": 4,
    "fret": 17,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 52.375,
    "duration": 0.125,
    "string": 4,
    "fret": 15,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 52.5,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 52.75,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 53,
    "duration": 0.25,
    "string": 4,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 53.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 53.5,
    "duration": 0.25,
    "string": 4,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 53.75,
    "duration": 0.125,
    "string": 4,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 53.875,
    "duration": 0.125,
    "string": 4,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 54,
    "duration": 0.25,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 54.25,
    "duration": 0.25,
    "string": 3,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 54.5,
    "duration": 0.25,
    "string": 4,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 54.75,
    "duration": 0.25,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 55,
    "duration": 0.25,
    "string": 4,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 55.25,
    "duration": 0.25,
    "string": 3,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 55.5,
    "duration": 0.25,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 55.75,
    "duration": 0.25,
    "string": 3,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 56,
    "duration": 1.25,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 57.25,
    "duration": 0.125,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 57.375,
    "duration": 0.125,
    "string": 3,
    "fret": 10,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 57.5,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 57.75,
    "duration": 1.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 59,
    "duration": 0.25,
    "string": 3,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 59.25,
    "duration": 0.125,
    "string": 3,
    "fret": 12,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 59.375,
    "duration": 0.125,
    "string": 3,
    "fret": 10,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 59.5,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 59.75,
    "duration": 1.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 61,
    "duration": 0.25,
    "string": 3,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 61.25,
    "duration": 0.125,
    "string": 3,
    "fret": 12,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 61.375,
    "duration": 0.125,
    "string": 3,
    "fret": 10,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 61.5,
    "duration": 0.25,
    "string": 3,
    "fret": 9,
    "technique": "slide",
    "vibrato": false
   },
   {
    "start": 61.75,
    "duration": 1.25,
    "string": 4,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 63,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 63.25,
    "duration": 0.75,
    "string": 4,
    "fret": 15,
    "technique": "release",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 64,
    "duration": 6,
    "string": 4,
    "fret": 13,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 71,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 71.25,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 71.5,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 71.75,
    "duration": 0.25,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 72,
    "duration": 0.5,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 72.5,
    "duration": 0.5,
    "string": 4,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 73,
    "duration": 0.5,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 73.5,
    "duration": 2,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 75.5,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 75.75,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 76,
    "duration": 0.5,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 76.5,
    "duration": 1,
    "string": 2,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 77.5,
    "duration": 2,
    "string": 4,
    "fret": 6,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 79.5,
    "duration": 0.25,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 79.75,
    "duration": 0.25,
    "string": 4,
    "fret": 5,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 80,
    "duration": 0.5,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 80.5,
    "duration": 0.5,
    "string": 4,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 81,
    "duration": 0.5,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 81.5,
    "duration": 2.5,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 84,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 84.25,
    "duration": 2.5,
    "string": 3,
    "fret": 7,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 86.75,
    "duration": 0.25,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 87,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 87.25,
    "duration": 0.25,
    "string": 3,
    "fret": 7,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 87.5,
    "duration": 0.25,
    "string": 3,
    "fret": 5,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 87.75,
    "duration": 0.25,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 88,
    "duration": 0.5,
    "string": 4,
    "fret": 6,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 88.5,
    "duration": 0.5,
    "string": 4,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 89,
    "duration": 0.5,
    "string": 3,
    "fret": 5,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 89.5,
    "duration": 2.5,
    "string": 2,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 92,
    "duration": 1,
    "string": 3,
    "fret": 7,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 93,
    "duration": 1,
    "string": 3,
    "fret": 9,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 94,
    "duration": 1,
    "string": 3,
    "fret": 10,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 95,
    "duration": 1,
    "string": 3,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 96,
    "duration": 1,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 97,
    "duration": 1,
    "string": 3,
    "fret": 16,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 98,
    "duration": 1,
    "string": 3,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 99,
    "duration": 1,
    "string": 3,
    "fret": 19,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 100,
    "duration": 3,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 103,
    "duration": 0.75,
    "string": 4,
    "fret": 20,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 103.75,
    "duration": 0.25,
    "string": 5,
    "fret": 20,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 104,
    "duration": 3.25,
    "string": 4,
    "fret": 20,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 107.25,
    "duration": 0.25,
    "string": 5,
    "fret": 20,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 107.5,
    "duration": 0.5,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 108,
    "duration": 1.5,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 109.5,
    "duration": 4.5,
    "string": 5,
    "fret": 19,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 114.5,
    "duration": 4,
    "string": 4,
    "fret": 17,
    "technique": "bend",
    "bend": 1,
    "vibrato": true
   },
   {
    "start": 118.5,
    "duration": 0.25,
    "string": 3,
    "fret": 19,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 118.75,
    "duration": 0.25,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 119,
    "duration": 0.25,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 119.25,
    "duration": 0.25,
    "string": 4,
    "fret": 20,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 119.5,
    "duration": 0.25,
    "string": 5,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 119.75,
    "duration": 0.25,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 120,
    "duration": 0.25,
    "string": 4,
    "fret": 20,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 120.25,
    "duration": 0.25,
    "string": 4,
    "fret": 17,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 120.5,
    "duration": 0.25,
    "string": 4,
    "fret": 18,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 120.75,
    "duration": 0.25,
    "string": 4,
    "fret": 20,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 121,
    "duration": 1,
    "string": 4,
    "fret": 17,
    "technique": "bend",
    "bend": 1,
    "vibrato": false
   },
   {
    "start": 122,
    "duration": 0.75,
    "string": 4,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 122.75,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 123,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 123.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 123.5,
    "duration": 0.25,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 123.75,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 124,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 124.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 124.75,
    "duration": 0.75,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 125.5,
    "duration": 0.25,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 125.75,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 126,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 126.25,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 126.75,
    "duration": 0.75,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": true
   },
   {
    "start": 127.5,
    "duration": 0.25,
    "string": 3,
    "fret": 14,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 127.75,
    "duration": 0.25,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 128,
    "duration": 0.5,
    "string": 5,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 128.5,
    "duration": 0.5,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 129,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 129.25,
    "duration": 0.125,
    "string": 5,
    "fret": 15,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 129.375,
    "duration": 0.125,
    "string": 5,
    "fret": 13,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 129.5,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 129.75,
    "duration": 0.25,
    "string": 5,
    "fret": 13,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 130,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 130.25,
    "duration": 0.125,
    "string": 5,
    "fret": 13,
    "technique": "hammer",
    "vibrato": false
   },
   {
    "start": 130.375,
    "duration": 0.125,
    "string": 5,
    "fret": 12,
    "technique": "pull",
    "vibrato": false
   },
   {
    "start": 130.5,
    "duration": 0.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 130.75,
    "duration": 0.25,
    "string": 5,
    "fret": 12,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 131,
    "duration": 0.5,
    "string": 4,
    "fret": 15,
    "technique": "bend",
    "bend": 2,
    "vibrato": false
   },
   {
    "start": 131.5,
    "duration": 0.25,
    "string": 5,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 131.75,
    "duration": 1.25,
    "string": 4,
    "fret": 15,
    "technique": null,
    "vibrato": false
   },
   {
    "start": 133,
    "duration": 3,
    "string": 4,
    "fret": 13,
    "technique": null,
    "vibrato": true
   }
  ],
  "gpUrl": "/gp/november-rain.gp5"
 }
];
